import { NewRole } from '../schema';

export const DEFAULT_ROLES: Omit<NewRole, 'institutionId'>[] = [
  {
    name: 'Board of Governors',
    hierarchyLevel: 1,
    isDefault: true,
    sendScope: {
      can_broadcast: true,
      can_target_roles: true,
      can_target_departments: true,
      can_target_individuals: true,
      max_hierarchy_level: 8,
    },
    contentAccess: { all: true },
    adminRights: { manage_institution: true, manage_roles: true },
  },
  {
    name: 'Principal',
    hierarchyLevel: 2,
    isDefault: true,
    sendScope: {
      can_broadcast: true,
      can_target_roles: true,
      can_target_departments: true,
      can_target_individuals: true,
      max_hierarchy_level: 8,
    },
    contentAccess: { all: true },
    adminRights: { manage_users: true },
  },
  {
    name: 'Deputy Principal',
    hierarchyLevel: 3,
    isDefault: true,
    sendScope: {
      can_broadcast: true,
      can_target_roles: true,
      can_target_departments: true,
      can_target_individuals: true,
      max_hierarchy_level: 8,
    },
    contentAccess: { all: true },
    adminRights: {},
  },
  {
    name: 'Head of Department',
    hierarchyLevel: 4,
    isDefault: true,
    sendScope: {
      can_broadcast: false,
      can_target_roles: ['trainer', 'trainee'],
      can_target_departments: false,
      can_target_individuals: true,
      max_hierarchy_level: 8,
    },
    contentAccess: { department: true },
    adminRights: {},
  },
  {
    name: 'Trainer',
    hierarchyLevel: 5,
    isDefault: true,
    sendScope: {
      can_broadcast: false,
      can_target_roles: ['trainee'],
      can_target_departments: false,
      can_target_individuals: true,
      max_hierarchy_level: 8,
    },
    contentAccess: { department: true },
    adminRights: {},
  },
  {
    name: 'Support Staff',
    hierarchyLevel: 6,
    isDefault: true,
    sendScope: {
      can_broadcast: false,
      can_target_roles: [],
      can_target_departments: false,
      can_target_individuals: false,
      max_hierarchy_level: 8,
    },
    contentAccess: { own: true },
    adminRights: {},
  },
  {
    name: 'Trainee',
    hierarchyLevel: 8,
    isDefault: true,
    sendScope: {
      can_broadcast: false,
      can_target_roles: [],
      can_target_departments: false,
      can_target_individuals: false,
      max_hierarchy_level: 8,
    },
    contentAccess: { own: true },
    adminRights: {},
  },
];
