/** [RBAC] Fixed role set — institutions never create custom roles. */
export enum Role {
  SUPER_ADMIN = 'SUPER_ADMIN',
  INSTITUTION_ADMIN = 'INSTITUTION_ADMIN',
  PRINCIPAL = 'PRINCIPAL',
  CHAIRPERSON = 'CHAIRPERSON',
  BOARD_MEMBER = 'BOARD_MEMBER',
  DEPUTY_PRINCIPAL_ACADEMICS = 'DEPUTY_PRINCIPAL_ACADEMICS',
  DEPUTY_PRINCIPAL_ADMIN = 'DEPUTY_PRINCIPAL_ADMIN',
  HOD = 'HOD',
  TRAINER = 'TRAINER',
  TRAINEE = 'TRAINEE',
}
